### ISSUE TITLE
Support negative shadow spread value 

### ISSUE THREAD

**Issue by AmjadHD** [treeform/pixie#372]
I want to create a shadow generated by this CSS:
```css
{
  box-shadow: 0 6px 12px -2px rgba(0, 0, 0, 0.4);
}
```
I get this error:
```
masks.nim(217)           spread
Error: unhandled exception: Cannot apply negative spread [PixieError]
```
